apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "myapp.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "127.0.0.1.nip.io"  # Use Minikube IP with nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "myapp.fullname" . }}-frontend-service
                port:
                  number: 80
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: {{ include "myapp.fullname" . }}-backend-service
                port:
                  number: 3000
          #- path: /kiali
           # pathType: Prefix
            #backend:
             # service:
              #  name: kiali
               # port:
                #  number: 20001
