apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "myapp.fullname" . }}-virtualservice
  namespace: default  # Adjust namespace as needed
spec:
  hosts:
    - "127.0.0.1.nip.io"  # Minikube IP with nip.io for external access
  gateways:
    - {{ include "myapp.fullname" . }}-gateway
  http:
    - match:
        - uri:
            prefix: /backend
      rewrite:
        uri: "/"  # Rewrite URI for backend requests
      route:
        - destination:
            host: {{ include "myapp.fullname" . }}-backend-service
            port:
              number: 3000
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: "/"  # Rewrite URI for frontend requests
      route:
        - destination:
            host: {{ include "myapp.fullname" . }}-frontend-service
            port:
              number: 80
